# Generated by Django 3.2 on 2021-06-16 09:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('appreview', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviereview',
            name='comment',
            field=models.CharField(default=django.utils.timezone.now, max_length=1000),
            preserve_default=False,
        ),
    ]
