# Generated by Django 3.2 on 2021-06-16 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appreview', '0003_moviereview_is_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviereview',
            name='is_like',
            field=models.IntegerField(default=0),
        ),
    ]
