# Generated by Django 3.2 on 2021-06-17 04:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appreview', '0004_alter_moviereview_is_like'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResetPhoneOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the form of +919999999999.', regex='^\\+?1?\\d{9,14}$')])),
                ('otp', models.CharField(blank=True, max_length=9, null=True)),
                ('count', models.IntegerField(default=0, help_text='Number of otp_sent')),
                ('validated', models.BooleanField(default=False, help_text='if it is true, that mean user have validate otp correctly in seconds')),
            ],
        ),
    ]
