# Generated by Django 3.2 on 2021-06-17 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appreview', '0005_resetphoneotp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resetphoneotp',
            name='count',
            field=models.IntegerField(default=0, help_text='Number of opt_sent'),
        ),
        migrations.AlterField(
            model_name='resetphoneotp',
            name='validated',
            field=models.BooleanField(default=False, help_text='if it is true, that mean user have validate opt correctly in seconds'),
        ),
    ]
