# Generated by Django 3.2 on 2021-06-18 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appreview', '0010_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
